# Generated by Django 3.1.4 on 2021-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210122_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate',
            new_name='rate_buy',
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_sell',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
