# Generated by Django 3.1.4 on 2021-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_delete_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate_buy',
            field=models.PositiveIntegerField(default=1, verbose_name='Курс покупки'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate_sell',
            field=models.PositiveIntegerField(default=1, verbose_name='Курс продажи'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Короткое наименование'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, verbose_name='Символ'),
        ),
    ]
