# Generated by Django 3.1.4 on 2021-01-22 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210118_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
