# Generated by Django 3.1.4 on 2021-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210122_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation_type',
            field=models.CharField(choices=[('Покупка', 'Покупка'), ('Продажа', 'Продажа')], default='Покупка', max_length=10),
        ),
    ]
