# Generated by Django 3.1.4 on 2021-01-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_type',
            field=models.CharField(choices=[('Покупка', 'Покупка'), ('Продажа', 'Продажа')], max_length=10),
        ),
    ]
